export const Keys = {
  OT_OCTOTREE: 'OT_OCTOTREE',
  OT_GITHUB: 'OT_GITHUB',
  OT_RELOAD_SEESSION: 'OT_RELOAD_SEESSION',
  OT_RELOAD: 'OT_RELOAD',
  OT_CODE_COLOR_THEME: 'OT_CODE_COLOR_THEME',
  OT_CODE_ICONS_THEME: 'OT_CODE_ICON_THEME',
};
